### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Jasonzyt** [Jasonzyt/QuickBackupX#2]
- [ ] Rewrite classes
- [ ] Use `nlohmann/json`
- [ ] Adapt to LiteLoader2.0
- [ ] Use json to record backups
- [ ] Update v143(VS 2022)
- [ ] {Git} Rename default branch `master` to `main`
- [ ] Rename files
